# -*- coding: utf-8 -*-
"""Conversão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i0h4Fmk5gAx0yyhkqJMyTfRL0gPU5q_g

Celsius para Fahrenheit
"""

C = float(input("Informe a Temperatura em Cº: "))
F = (C * 9/5) + 32

print(f"A temperatura {C}º Celsius é {F}º Fahrenheit")

"""Celsius para Kelvin"""

C = float(input("Informe a Temperatura em Cº: "))
K = (C + 273,15)

print(f"A temperatura {C}º Celsius é {K}º Kelvin")

"""Menu Temperatura

"""

'''Menu Temperatura'''
print("Conversão de Temperatura:")

print(" 1- Celsius para Fahrenheit\n 2- Fahrenheit para Celsius\n 3- Celsius para Kelvin\n 4- Kelvin para Celsius\n 5- Fahrenheit para Kelvin\n 6- Kelvin para Fahrenheit")

while True:
  opc = int(input("Selecione qual a conversão a fazer: "))
  print()
  if opc == 1:
    C = float(input("Informe a Temperatura em Cº: "))
    F = (C * 9/5) + 32
    print(f"A temperatura {C:.2f}ºC é {F:.2f}ºF")
    break
  elif opc == 2:
    F = float(input("Informe a Temperatura em Fº: "))
    C = (F - 32) * 5/9
    print(f"A temperatura {F:.2f}ºF é {C:.2f}ºC")
    break
  elif opc == 3:
    C = float(input("Informe a Temperatura em Cº: "))
    K = (C + 273.15)
    print(f"A temperatura {C:.2f}ºC é {K:.2f}ºK")
    break
  elif opc == 4:
    K = float(input("Informe a Temperatura em Kº: "))
    C = (K - 273.15)
    print(f"A temperatura {K:.2f}ºK é {C:.2f}ºC")
    break
  elif opc == 5:
    F = float(input("Informe a Temperatura em Fº: "))
    K = (F - 32) * 5/9 + 273.15
    print(f"A temperatura {F:.2f}ºF é {K:.2f}ºK")
    break
  elif opc == 6:
    K = float(input("Informe a Temperatura em Kº: "))
    F = (K - 273.15) * 9/5 + 32
    print(f"A temperatura {K:.2f}ºK é {F:.2f}ºF")
    break
  else:
    print("Opção incorreta!!")
    break

