# -*- coding: utf-8 -*-
"""Funcoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UjZyehyk5F4lF0F4haja09ozP9-dx_v7

Função EX1
"""

def funcao():
  print("Teste")
funcao()

"""Função EX2

"""

def soma(x, y):
  print(x+y)
  return 
v1 = 10
v2 = 20
soma(v1, v2)

"""Função Fahrenheit"""

def fahrenheit(x):
  F = (x * 9/5) + 32
  print(f"{x}ºC é {F}ºF")
  return F

fahrenheit(25)

"""Função ao Quadrado"""

def quadrado(x): #ou def quadrado():
  # x = float(input("Informe seu número: "))
  if x == 0:
    print("Não existe 0²!")
  else:
    q = x**2
    print(f"{x}² é {q}")
    return q

#quadrado() <-- informar qualquer valor
print(quadrado(float(input("Informe um número: ")))) # ENCAPSULADO

"""Função Devolver Maior"""

def maior():
  x = float(input("Informe o primeiro valor: "))
  y = float(input("Informe o segundo valor: "))
  if x > y:
    '''print(f"{x} é maior que {y}")'''
    return x
  elif x == y:
    '''print(f"{x} e {y} são iguais")'''
    return x
  else:
    '''print(f"{y} é maior que {x}")'''
    return y
maior()

"""Função 3 notas"""

def media():
  soma = 0
  for x in range(0,3):
    nota = float(input(f"Informe a {x+1}ª nota: "))
    soma += nota
  media = soma / 3

  if media >= 7:
    print(f"Sua média é {media:.1f}")
    print("Aprovado!")
  elif 5 <= media < 7:
    print(f"Sua média é {media:.1f}")
    print("Recuperação!")
  else:
    print(f"Sua média é {media:.1f}")
    print("Reprovado!")

media()

"""Função mais notas

"""

def medias():
  notas = []
  for x in range(0,10):
    n = float(input(f"Informe a {x+1}ª nota: "))
    notas.append(n)
  
  media = sum(notas) / len(notas)

  if media >= 7:
    print(f"Sua média é {media:.1f}")
    print("Aprovado!")
  elif 5 <= media < 7:
    print(f"Sua média é {media:.1f}")
    print("Recuperação!")
  else:
    print(f"Sua média é {media:.1f}")
    print("Reprovado!")

  print(media)

medias()