# -*- coding: utf-8 -*-
"""Matriz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfRlMhKP3FlH_LyVPiTd-tvcZ2mUlTlf
"""

tam = int(input("Insira o tamanho da matriz: "))
matriz = [[0 for i in range(tam)] for j in range(tam)]

for i in range(0, tam):
    for j in range(0, tam):
        if i <= j:
            matriz[i][j] = int(input(f"Insira um valor na matriz {i+1} X {j+1}: "))
        else:
            continue
        
for i in range(0, tam):
    for j in range(0, tam):
        print(f"[{matriz[i][j]:^5}]", end="")
    print()

'''
  Desenvolvido por: Matheus Oliveira Nonato da Silva
                    Nathalia Cristina Silva Senna
  Matéria: Álgebra linear
  Professora: Janaina Stella de Sousa
  Data: 18/02/2022
  Objetivo: Leia o tamanho de uma matriz quadrada
            Carregue os elementos da matriz triangular superior do tamanho acima
            Retorne a matriz triangular superior completa
'''
tam = int(input("Insira o tamanho da matriz: ")) # Tamanho da matriz sendo informado pelo usuário
if tam <= 0: # Verifica se o tamanho da matriz é maior de 0
  print("Insira um valor maior que 0! ")
  
matriz = [[0 for i in range(tam)] for j in range(tam)] # Cria uma matriz de zeros (0) a partir do tamanho informado pelo usuário

for i in range(0, tam): # Cria as linhas da matriz
    for j in range(0, tam): # Cria as colunas da matriz
        if i <= j: # Verifica se o tamanho da coluna é maior que o tamanho da linha 
            matriz[i][j] = int(input(f"Insira um valor na matriz {i+1} X {j+1}: ")) # Insere um valor sempre que passar pelo if
        else:
            continue
        
for i in range(0, tam): 
    for j in range(0, tam):
        print(f"[{matriz[i][j]:^5}]", end="") # Mostra a matriz para o usuário
    print()